services:
  wbor-bot:
    image: wborfm/discord-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STATION_API_URL=https://azura.wbor.org/api/station/2
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./persist:/app/persist
    restart: unless-stopped

volumes:
  persist:
    driver: local
