version: "2.2"

services:
  azuri:
    image: wborfm/discord-bot:latest
    build:
      context: .
    env_file: azuri.env
    volumes:
      - ./src:/data
      - azuri_persist:/data/persist

volumes:
  azuri_persist: {}
  azuri_node_modules: {}
